import openai
import os
import logging

# Set up logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

# Set the OpenAI API key from environment variables
openai.api_key = os.getenv("OPENAI_API_KEY")

def ask_openai(prompt, model="text-davinci-003", max_tokens=150):
    """
    Send a prompt to the OpenAI API and return the generated response.

    Args:
        prompt (str): The input prompt to send to the OpenAI model.
        model (str, optional): The OpenAI model to use. Defaults to "text-davinci-003".
        max_tokens (int, optional): The maximum number of tokens to generate. Defaults to 150.

    Returns:
        str: The text generated by the OpenAI model in response to the prompt.
    """
    try:
        response = openai.Completion.create(
            engine=model,
            prompt=prompt,
            max_tokens=max_tokens
        )
        return response.choices[0].text.strip()
    except openai.error.OpenAIError as e:
        logging.error(f"OpenAI API error: {e}")
        return None
    except Exception as e:
        logging.error(f"Unexpected error: {e}")
        return None

# Example usage
if __name__ == "__main__":
    prompt = "Write a short story about a cat who can talk."
    response = ask_openai(prompt, model="text-davinci-003", max_tokens=200)
    if response:
        print(response)
